// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
//  import 'firebase_options.dart';
// /// // ...
// await Firebase.initializeApp(
//     options: DefaultFirebaseOptions.currentPlatform,
// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhCXq3Q8biBeMMH9oMJBo-X-wn3CX6ei0',
    appId: '1:7997260111:web:c7022d7bbe59004a13853a',
    messagingSenderId: '7997260111',
    projectId: 'eatup-f145e',
    authDomain: 'eatup-f145e.firebaseapp.com',
    storageBucket: 'eatup-f145e.appspot.com',
    measurementId: 'G-VE77D22KH4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdMzLb6OS1CRyjnear8Qo8X3RBCYniitA',
    appId: '1:7997260111:ios:6b759205df067f4f13853a',
    messagingSenderId: '7997260111',
    projectId: 'eatup-f145e',
    storageBucket: 'eatup-f145e.appspot.com',
    iosBundleId: 'com.example.eatup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhCXq3Q8biBeMMH9oMJBo-X-wn3CX6ei0',
    appId: '1:7997260111:web:a6aa278ea2cfef4813853a',
    messagingSenderId: '7997260111',
    projectId: 'eatup-f145e',
    authDomain: 'eatup-f145e.firebaseapp.com',
    storageBucket: 'eatup-f145e.appspot.com',
    measurementId: 'G-9SK1NCEXZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP0bTs_53ffjMTQ5CqMbvGWkOkpe07vNo',
    appId: '1:7997260111:android:86a47af23e31450013853a',
    messagingSenderId: '7997260111',
    projectId: 'eatup-f145e',
    storageBucket: 'eatup-f145e.appspot.com',
  );
}
